// Maps iconKey from achievementData to react-icons (Fi) for Achievements & Recognition
import {
  FiAward,
  FiTrendingUp,
  FiStar,
  FiHeart,
  FiUsers,
  FiCpu,
  FiTarget,
  FiZap,
  FiCheckCircle,
  FiBriefcase,
  FiBook,
  FiArrowRight,
  FiImage,
  FiFilter,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiCheck,
  FiSearch,
  FiEye,
  FiX,
  FiMail,
  FiCalendar,
  FiMapPin,
  FiShare2,
  FiMessageCircle,
  FiClock,
  FiUser,
  FiPlus,
} from 'react-icons/fi';
import { FaQuoteLeft, FaLinkedinIn, FaCrown } from 'react-icons/fa';

export const ACHIEVEMENT_ICONS = {
  medal: FiAward,
  trophy: FiAward,
  crown: FaCrown,
  star: FiStar,
  heart: FiHeart,
  handHeart: FiHeart,
  rocket: FiZap,
  certificate: FiCheckCircle,
  trendUp: FiTrendingUp,
  code: FiCpu,
  target: FiTarget,
  users: FiUsers,
  sparkle: FiStar,
  briefcase: FiBriefcase,
  graduationCap: FiBook,
  arrowRight: FiArrowRight,
  image: FiImage,
  funnel: FiFilter,
  caretDown: FiChevronDown,
  caretLeft: FiChevronLeft,
  caretRight: FiChevronRight,
  check: FiCheck,
  search: FiSearch,
  eye: FiEye,
  x: FiX,
  mail: FiMail,
  calendar: FiCalendar,
  mapPin: FiMapPin,
  share: FiShare2,
  messageCircle: FiMessageCircle,
  quotes: FaQuoteLeft,
  linkedin: FaLinkedinIn,
  clock: FiClock,
  confetti: FiZap,
  user: FiUser,
  plus: FiPlus,
};

export default ACHIEVEMENT_ICONS;
